version: '3.9'

services:
  db: 
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cards
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js
