version: '3.9'

services:
  db: 
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cards
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js

  backend:
    build: ./api
    ports:
      - 3000:80
    depends_on:
      - db
    env_file: ./api/.env
    volumes:
      - ./api/src:/app/src
  
  # frontend:
  #   build: ./web
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - backend
  #   env_file: ./frontend/.env
  #   volumes:
  #     - ./frontend/src:/app/src